public class Complement {
    public String complementing(String dna) {
        String copy = "";
        for(int i = 0; i<dna.length(); i++){
            if(dna.charAt(i) == 'A'){
                copy = copy + 'T';
            }
            if(dna.charAt(i) == 'T'){
                copy = copy + 'A';
            }
            if(dna.charAt(i) == 'C'){
                copy = copy + 'G';
            }
            if(dna.charAt(i) == 'G'){
                copy = copy + 'C';
            }
        }
        String ret = reversed(copy);
        System.out.println(ret.toString());

        return ret;

    }
    private String reversed (String comp){
        String rev = "";
        for (int i = 0; i < comp.length(); i++){
            rev = comp.charAt(i) + rev;
        }
        return rev;
    }
    public static void main(String[] args) {
        Complement a = new Complement();
        //String s = "GCTATCCTTTAGTAGGTTACATGGCGGTCGTCCACGTACTGCGGAAATGCAAGCGTCTCCCTCGATGTGCTTTGGCGTGCTCGAACGCACTTCAGAAGAAATTAGCAAACACGTTTCGCGTCTAAACCCACTACTGTAAATGACGATACCTTTTTCGGTGATGCTACAGACTCGTGTCATTGACGGGTCATCATCGCTATCATGTTCTGCGAGTCTCTCACACTGTCAGACTACAGCTGTCGTCGGGACAGGTAGCATATTTAGATAGGACTTTACGTGCGGACGGGTGTAACCGGGCGTATAGCTCGAGGTTTAATCTTACTCCAAGATACGTGGGAGCTTGATAGGTGCCTAATCTGCTCTGTGATGTCACCGCCCTAGACGGCGGCTACCGATAGAGTATTGACCATCTCACGGTGTACGTTCACGAGCCCTAGCATGCTGTGCGAGGGGTTGCGTAATACGGTCTGACGGACGAACTCTGCCGACCACTCGACAGCCATCCTTGATTGTCAGCACTAAAATCGATCCAACATTGTGGGCATCAGGTAGTACTGGTTTAGAGAAGCCGGCCGAGGTGTGGGACCTTTCGGAGGTCAACATCCTGATTCGTTTCACTAGGTATCATGTCTGTTGCCAGTGAAAGCCCGAAGAGGATATGCGGTCCGCAAACCCAGGTGACCAGCTTGTAAGTAGCCAAATTAACTGCGCGTTTGTACCTGACAATTAATGTAGCGCGAGTAACGTAAAGGTCTCGAGACAGGCCGTGCGGAAACACCTCATCAATGTACTTGGGCCCACCGTACTTAAGGTG";
        //String bean = "TCAGAGATAGACTCGGAGCATTCATAAGCAGGTCACCTCGCGTTAACGCAAGCTGCTGTAAAGCTTTGCGTGGTCCCTGCGTTGAGCGTTTTGAGGCAAATTTAAGGGGGGACTCCCCTGCTACCTGGATCCGAATATTTCCGTCTTCTTTCTACCCCTTCATTTCACAAATTTTACAGGGTTATAGGTCGCTGAGCTGTATGTGTAATAACCGGCTCATCACGAGGGAGCGAGGGTTCTACACAACCCGTAGTCTCTATTCATGCGACCGTGATTACCACGAAGGCTCATGTCACGCTAGGCGGAGCGCGAGGCAAACGCCGCTACGTTGCAGTTCCATGTTGAATGTTCGTCGGGGAACACGACTGATCCTGTGCGCCCCCGACCCAAACATAGGATTTAGTCGTGCGGTTTAACCGATAGCGGACCGGGATAGAGATGGTGACAGGCCCCAAGTGACGGGATCGGACTGACGCTTCAAACAGGACAGCCGTGGGACAAAGCAAGAGTACTTGCCCTCCTTGCTAAATTTCTTAAGAAACCGGCCACTGCACAACAAAACCATTATCATCGTAGTAGCTTTCATACCGCACTATGCCCCGAGACTTATTATAATGAATCGTCTCGTCTACCTTTATTTACAATTCAACACGCGCTCTGGGGAGGACCAACCCATGAGTTTAATACTGGGGGTACAGGCCAGGTAGCTGGTAAACCAGATTCCGGTACACCGTATCATCGTGCCATAATTACCGGCAATCGATTGCCGCAGTTGGTGCCAGACGTACTCCCAGACACAGAACTGAAGTTCTTATAAAGAGTTCTGCGTCTATGGGTATTGG";
        //String pop = "GATGGAACTTGACTACGTAAATT";
        String roz = "ATAGGCCAGGGTGGTTAGCGCCGCGGGACTCTGTTGTGCCAGATACTGTGCCGCAGGCTATATATTATTAATCGACCTTCGGATGTTCAACGGGACCTGCGCCATAGTCGCATACCCGCTCGAGGGACACTGCTGGGGGTGCGATCTTCGGATCCCGCTAGAGAGGAGAGGAGCAGACTCTGCCCGTGATGCAACGGGGTAGTAGGCAAAGACTACTCCAAGGCAAGCACTTCTTTAAGTCACGCGTCTAATCATGGAAAATTACTTCTTGTGCTACGATTCCTGCAATACGCACGTCAGGAGCAATATGTTTAAGTAAGCTTCTTACATCAACCCGCTGTATCCTTACTAGAGTGATTTTTAATGCCAGCGATGTATATTCTGTGACATGAAGGCAGTGGATTCGATTGTTGTAGTTTGAGACGGCCTCCCCAGAAGAGAGATTGGAGTATGATTCGATCGGGTATATCCTGTTCCGGTGTGACGGAACCAAACTGGGCGGTTGCACTTTAAGAGCAGAAGATATCGTTTAGACTTCCTTAACACGAGAAGCAACGGGAACAGGTCGTTAGGTCCGCACATTGAGCGGTGTAACCTGTTAGGTAAATAATGCCCAACCTAGCACGCATTCCTTGCCGTGAAGTTTGTCCCATCGACCAATGATTCCCTAAGGACGCCTTTTGAAACCCCACCGGCTGCCACTCTATGGCTCACTTCTCTGAACCCATCCGCTATTAGGAGCCCGGGATCATTCGGGCAGACTAGAGTTAGCAATTAAGAATTGAGCTAACCAGCCCTCTGGCTATAAAATCAAACCTACTACCCCAGACTTCATGTAATTGAATGTACTTCCGATCCTCCGCCCCATCAGCCCCTGTAATAGACACGCTATATCTTTATGCTACACG";
        //System.out.println(a.counting(s));
        a.complementing(roz);
    }
}
