import java.util.Arrays;
import java.util.Collections;
import java.util.HashMap;
import java.util.TreeSet;

public class DNAcounting {
        public int[] counting(String dna) {
            String[] splice = dna.split("");
            HashMap<String, Integer> dnamap = new HashMap<>();
            TreeSet<String> dnastring = new TreeSet<>(Arrays.asList(splice));
            for (String s : splice) {
                int counter = Collections.frequency(Arrays.asList(splice.clone()), s);
                dnamap.put(s, counter);
            }
            System.out.println(dnamap.toString());

            return null;
        }

        public static void main(String[] args) {
            DNAcounting a = new DNAcounting();
            //String s = "GCTATCCTTTAGTAGGTTACATGGCGGTCGTCCACGTACTGCGGAAATGCAAGCGTCTCCCTCGATGTGCTTTGGCGTGCTCGAACGCACTTCAGAAGAAATTAGCAAACACGTTTCGCGTCTAAACCCACTACTGTAAATGACGATACCTTTTTCGGTGATGCTACAGACTCGTGTCATTGACGGGTCATCATCGCTATCATGTTCTGCGAGTCTCTCACACTGTCAGACTACAGCTGTCGTCGGGACAGGTAGCATATTTAGATAGGACTTTACGTGCGGACGGGTGTAACCGGGCGTATAGCTCGAGGTTTAATCTTACTCCAAGATACGTGGGAGCTTGATAGGTGCCTAATCTGCTCTGTGATGTCACCGCCCTAGACGGCGGCTACCGATAGAGTATTGACCATCTCACGGTGTACGTTCACGAGCCCTAGCATGCTGTGCGAGGGGTTGCGTAATACGGTCTGACGGACGAACTCTGCCGACCACTCGACAGCCATCCTTGATTGTCAGCACTAAAATCGATCCAACATTGTGGGCATCAGGTAGTACTGGTTTAGAGAAGCCGGCCGAGGTGTGGGACCTTTCGGAGGTCAACATCCTGATTCGTTTCACTAGGTATCATGTCTGTTGCCAGTGAAAGCCCGAAGAGGATATGCGGTCCGCAAACCCAGGTGACCAGCTTGTAAGTAGCCAAATTAACTGCGCGTTTGTACCTGACAATTAATGTAGCGCGAGTAACGTAAAGGTCTCGAGACAGGCCGTGCGGAAACACCTCATCAATGTACTTGGGCCCACCGTACTTAAGGTG";
            String bean = "TCAGAGATAGACTCGGAGCATTCATAAGCAGGTCACCTCGCGTTAACGCAAGCTGCTGTAAAGCTTTGCGTGGTCCCTGCGTTGAGCGTTTTGAGGCAAATTTAAGGGGGGACTCCCCTGCTACCTGGATCCGAATATTTCCGTCTTCTTTCTACCCCTTCATTTCACAAATTTTACAGGGTTATAGGTCGCTGAGCTGTATGTGTAATAACCGGCTCATCACGAGGGAGCGAGGGTTCTACACAACCCGTAGTCTCTATTCATGCGACCGTGATTACCACGAAGGCTCATGTCACGCTAGGCGGAGCGCGAGGCAAACGCCGCTACGTTGCAGTTCCATGTTGAATGTTCGTCGGGGAACACGACTGATCCTGTGCGCCCCCGACCCAAACATAGGATTTAGTCGTGCGGTTTAACCGATAGCGGACCGGGATAGAGATGGTGACAGGCCCCAAGTGACGGGATCGGACTGACGCTTCAAACAGGACAGCCGTGGGACAAAGCAAGAGTACTTGCCCTCCTTGCTAAATTTCTTAAGAAACCGGCCACTGCACAACAAAACCATTATCATCGTAGTAGCTTTCATACCGCACTATGCCCCGAGACTTATTATAATGAATCGTCTCGTCTACCTTTATTTACAATTCAACACGCGCTCTGGGGAGGACCAACCCATGAGTTTAATACTGGGGGTACAGGCCAGGTAGCTGGTAAACCAGATTCCGGTACACCGTATCATCGTGCCATAATTACCGGCAATCGATTGCCGCAGTTGGTGCCAGACGTACTCCCAGACACAGAACTGAAGTTCTTATAAAGAGTTCTGCGTCTATGGGTATTGG";
            //System.out.println(a.counting(s));
            a.counting(bean);
        }
}
