public class MaxDNA {
        public String max(String[] strands, String nuc) {
            String ret = "";
            int max = 1;
            for (String s : strands) {
                int nc = count(s, nuc);
                if (nc > max ||
                        (nc == max && s.length() > ret.length())) {
                    ret = s;
                    max = nc;
                }
            }
            System.out.println(ret.toString());
            return ret;
        }

        private int count(String s, String nuc) {
            int t = s.length() - s.replace(nuc, "").length();
            return t;
        }
    public static void main(String[] args) {
        MaxDNA a = new MaxDNA();
        //String s = "GCTATCCTTTAGTAGGTTACATGGCGGTCGTCCACGTACTGCGGAAATGCAAGCGTCTCCCTCGATGTGCTTTGGCGTGCTCGAACGCACTTCAGAAGAAATTAGCAAACACGTTTCGCGTCTAAACCCACTACTGTAAATGACGATACCTTTTTCGGTGATGCTACAGACTCGTGTCATTGACGGGTCATCATCGCTATCATGTTCTGCGAGTCTCTCACACTGTCAGACTACAGCTGTCGTCGGGACAGGTAGCATATTTAGATAGGACTTTACGTGCGGACGGGTGTAACCGGGCGTATAGCTCGAGGTTTAATCTTACTCCAAGATACGTGGGAGCTTGATAGGTGCCTAATCTGCTCTGTGATGTCACCGCCCTAGACGGCGGCTACCGATAGAGTATTGACCATCTCACGGTGTACGTTCACGAGCCCTAGCATGCTGTGCGAGGGGTTGCGTAATACGGTCTGACGGACGAACTCTGCCGACCACTCGACAGCCATCCTTGATTGTCAGCACTAAAATCGATCCAACATTGTGGGCATCAGGTAGTACTGGTTTAGAGAAGCCGGCCGAGGTGTGGGACCTTTCGGAGGTCAACATCCTGATTCGTTTCACTAGGTATCATGTCTGTTGCCAGTGAAAGCCCGAAGAGGATATGCGGTCCGCAAACCCAGGTGACCAGCTTGTAAGTAGCCAAATTAACTGCGCGTTTGTACCTGACAATTAATGTAGCGCGAGTAACGTAAAGGTCTCGAGACAGGCCGTGCGGAAACACCTCATCAATGTACTTGGGCCCACCGTACTTAAGGTG";
        String bean = "TCAGAGATAGACTCGGAGCATTCATAAGCAGGTCACCTCGCGTTAACGCAAGCTGCTGTAAAGCTTTGCGTGGTCCCTGCGTTGAGCGTTTTGAGGCAAATTTAAGGGGGGACTCCCCTGCTACCTGGATCCGAATATTTCCGTCTTCTTTCTACCCCTTCATTTCACAAATTTTACAGGGTTATAGGTCGCTGAGCTGTATGTGTAATAACCGGCTCATCACGAGGGAGCGAGGGTTCTACACAACCCGTAGTCTCTATTCATGCGACCGTGATTACCACGAAGGCTCATGTCACGCTAGGCGGAGCGCGAGGCAAACGCCGCTACGTTGCAGTTCCATGTTGAATGTTCGTCGGGGAACACGACTGATCCTGTGCGCCCCCGACCCAAACATAGGATTTAGTCGTGCGGTTTAACCGATAGCGGACCGGGATAGAGATGGTGACAGGCCCCAAGTGACGGGATCGGACTGACGCTTCAAACAGGACAGCCGTGGGACAAAGCAAGAGTACTTGCCCTCCTTGCTAAATTTCTTAAGAAACCGGCCACTGCACAACAAAACCATTATCATCGTAGTAGCTTTCATACCGCACTATGCCCCGAGACTTATTATAATGAATCGTCTCGTCTACCTTTATTTACAATTCAACACGCGCTCTGGGGAGGACCAACCCATGAGTTTAATACTGGGGGTACAGGCCAGGTAGCTGGTAAACCAGATTCCGGTACACCGTATCATCGTGCCATAATTACCGGCAATCGATTGCCGCAGTTGGTGCCAGACGTACTCCCAGACACAGAACTGAAGTTCTTATAAAGAGTTCTGCGTCTATGGGTATTGG";
        //System.out.println(a.counting(s));
        String[] str = {"A","G","T"};
        a.max(str, bean);
    }
}

